# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bigquery-app-deployment
  namespace: bigquery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bigquery-app
  template:
    metadata:
      labels:
        app: bigquery-app
    spec:
      containers:
        - name: bigquery-app
          image: gcr.io/google-samples/service-catalog/bigquery-user:latest
          volumeMounts:
            - name: service-account
              mountPath: /var/secrets/service-account
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/service-account/privateKeyData
            - name: BIGQUERY_PROJECT
              valueFrom:
                secretKeyRef:
                  name: user-bigquery-binding
                  key: projectId
            - name: BIGQUERY_DATASET
              valueFrom:
                secretKeyRef:
                  name: user-bigquery-binding
                  key: datasetId
          ports:
            - containerPort: 8080
      volumes:
        - name: service-account
          secret:
            secretName: user-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: bigquery-app-service
  namespace: bigquery
  labels:
    app: bigquery-app
spec:
  selector:
    app: bigquery-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
