# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: guestbook
  namespace: spanner-guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: guestbook
          image: gcr.io/google-samples/service-catalog/cloud-spanner-user:latest
          imagePullPolicy: Always
          volumeMounts:
            # Mount the secret volume into the container file system.
            - name: service-account
              mountPath: /var/secrets/credentials
          env:
            # Pass the path to the private key JSON file in the environment
            # variable.
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/credentials/privateKeyData

            # Both environment variables below come from the same secret
            # and, together, point at the Spanner instance to use.
            - name: SPANNER_PROJECT
              valueFrom:
                secretKeyRef:
                  # Use the projectId value from the user-spanner-binding secret
                  # created as a result of binding to the spanner instance.
                  name: user-spanner-binding
                  key: projectId
            - name: SPANNER_INSTANCE
              valueFrom:
                secretKeyRef:
                  # Use the instanceId value from the user-spanner-binding secret
                  # created as a result of binding to the spanner instance.
                  name: user-spanner-binding
                  key: instanceId
          ports:
            - containerPort: 8080
      volumes:
        # Make the user-account-credentials secret available as a volume.
        - name: service-account
          secret:
            secretName: user-account-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  namespace: spanner-guestbook
  labels:
    app: guestbook
spec:
  selector:
    app: guestbook
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
